def reportes(p_tarjeta):
  tar = p_tarjeta
  print("\n"*2)
  print("-" * 50)
  print("Resumen de la tarjeta")
  print("-" * 50)
  print("Nombre de la Franquicia: {}".format(tar.nombre))
  print("Tasa Interes Anual: % {:0,.2f}".format(tar.tasa))
  print("-" * 50)
  print("Deuda Actual: $ {:0,.2f}".format(tar.deuda))
  print("Pago: $ {:0,.2f}".format(tar.pago))
  print("-" * 50)
  print("Nueva Deuda: $ {:0,.2f}".format(tar.deuda-tar.pago))
  print("Interes Mensual: $ {:0,.2f}".format(tar.cargos_tarjeta.interes_mensual))
  print("-" * 50)
  print("Deuda Recalculada: $ {:0,.2f}".format(tar.cargos_tarjeta.deuda_calculada_mes))
  print("Nuevos Cargos: $ {:0,.2f}".format(tar.cargos))
  print("-" * 50)
  print("Nueva Deuda: $ {:0,.2f}".format(tar.cargos_tarjeta.nueva_deuda))